spring:

  kafka:
    properties:
      spring:
        json:
          trusted:
            packages: '*'

    consumer:
      group-id: messages-consumers
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092

app:

  topics:
    messages: messages